services:
  mia-x-central:
    image: alpine:latest
    container_name: MIAX_CENTRAL_CHILE
    restart: always
    networks:
      apiary_mesh: { ipv4_address: 10.5.0.2 }
    command: /bin/sh -c "while true; do sleep 3600; done"

  nodo-latam-sync:
    image: alpine:latest
    container_name: QVE_LATAM_NODES
    depends_on: [mia-x-central]
    networks:
      apiary_mesh: { ipv4_address: 10.5.0.3 }
networks:
  apiary_mesh:
    driver: bridge
    ipam:
      config: [{ subnet: 10.5.0.0/16 }]
